### ISSUE TITLE
error

### ISSUE THREAD

**Issue by juanquy** [ErwinSteffens/darksky-influxdb#1]
DarkSky data will be written to InfluxDB on cron interval '*/10 * * * *'
/home/sdsadmin/darksky2influxdb/importForecast.js:71
            var daily = forecast.daily;
                                 ^

TypeError: Cannot read property 'daily' of null
    at /home/sdsadmin/darksky2influxdb/importForecast.js:71:34
    at Request._callback (/home/sdsadmin/darksky2influxdb/node_modules/darksky-node/lib/darksky-api.js:34:13)
    at Request.self.callback (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/sdsadmin/darksky2influxdb/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)

I was thinking it was a problem with my location and Darksky but this work:

https://api.darksky.net/forecast/MY KEY HERE/38.4039,-96.1817

so it's not an issue with location.

any ideas?
regards 
JC

**Comment by ErwinSteffens** [comment]
No, I have no idea, but I do not recognise the code. Did you post this in the correct repository?

If so, do you have an reproduction?

**Comment by cagnulein** [comment]
sorry, it's my fault.

**Comment by cagnulein** [comment]
if you accept the pull request should be fine
